
import { Provider } from "react-redux";
import ContextAPI from "./components/ContextAPI/ContextAPI";
import NavBar from "./components/Navbar/Navbar";
import "./globals.css";
import { store } from "./components/Redux/Store";
import ReduxProvider from "./components/Redux/ReduxProvider";
import TankStackQuery from "./components/Hooks/TankStackQuery";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <TankStackQuery>
          <ReduxProvider>
            <ContextAPI>
              {children}
            </ContextAPI>
          </ReduxProvider>
        </TankStackQuery>
      </body>
    </html>
  );
}
