
import { Provider } from "react-redux";
import ContextAPI from "./components/ContextAPI/ContextAPI";
import NavBar from "./components/Navbar/Navbar";
import "./globals.css";
import { store } from "./components/Redux/Store";
import ReduxProvider from "./components/Redux/ReduxProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
        <ReduxProvider>
          <ContextAPI>
            <NavBar></NavBar>
            {children}
          </ContextAPI>
        </ReduxProvider>
      </body>
    </html>
  );
}
