
import ContextAPI from "./components/ContextAPI/ContextAPI";
import NavBar from "./components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
       <ContextAPI>
       <NavBar></NavBar>
       {children}
       </ContextAPI>
      </body>
    </html>
  );
}
